export const UPDATE_DATA = "UPDATE_DATA"
export const FETCH_PRODUCT = "FETCH_PRODUCT"
export const ADD_TO_CART = "ADD_TO_CART"
export const REMOVE_PRODUCT = "REMOVE_PRODUCT"
export const ORDER_CREATE = 'ORDER_CREATE'